name: Flutter Desktop Deployment

on:
  push:
    branches:
      - Main
    paths:
      - "versionNumber.txt"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Get version
        working-directory: ./cerberus
        id: vars
        run: echo "version=$(cat versionNumber.txt)" >> $GITHUB_OUTPUT
      - name: Install os dependencies
        run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - name: Install project dependencies
        working-directory: ./cerberus
        run: flutter pub get
      - name: Generate intermediates
        working-directory: ./cerberus
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable linux build
        working-directory: ./cerberus
        run: flutter config --enable-linux-desktop
      - name: Build artifacts
        working-directory: ./cerberus
        run: flutter build linux --release
      - name: Package Release files
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: cerberus-${{GITHUB_OUTPUT}}-linux.zip
          directory: cerberus/build/linux/x64/release/bundle
      - name: Release to github
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{GITHUB_OUTPUT}}
          files: cerberus/build/linux/x64/release/bundle/cerberus-${{GITHUB_OUTPUT}}-linux.zip

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install project dependencies
        working-directory: ./cerberus
        run: flutter pub get
      - name: Generate intermediates
        working-directory: ./cerberus
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable windows build
        working-directory: ./cerberus
        run: flutter config --enable-windows-desktop
      - name: Build artifacts
        working-directory: ./cerberus
        run: flutter build windows --release
      - name: Package Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: cerberus-${{github.ref_name}}-windows.zip
          directory: cerberus/build/windows/runner/Release
      - name: Release to github
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref_name}}
          files: cerberus/build/windows/runner/Release/cerberus-${{github.ref_name}}-windows.zip
