name: Flutter Desktop Deployment


on:
  workflow_dispatch
jobs:
  linux:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install os dependencies
        run: sudo apt update && sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - name: Install project dependencies
        working-directory: ./cerberus
        run: flutter pub get
      - name: Generate intermediates
        working-directory: ./cerberus
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable linux build
        working-directory: ./cerberus
        run: flutter config --enable-linux-desktop
      - name: Define enviornment variable
        working-directory: ./cerberus
        run: echo ${{ secrets.AUTH }} && echo ${{ secrets.AUTH }} > .env && cat .env
      - name: Build artifacts
        working-directory: ./cerberus
        run: flutter build linux --release
      - name: Package Release files
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: cerberus-${{github.ref_name}}-linux.zip
          directory: cerberus/build/linux/x64/release/bundle
      - name: Release to github
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref_name}}
          files: cerberus/build/linux/x64/release/bundle/cerberus-${{github.ref_name}}-linux.zip
    
